### ISSUE TITLE
One problem about rouge

### ISSUE THREAD

**Issue by Jimmy5217** [ymfa/seq2seq-summarizer#19]
I'm now running this model on Colab, but there is one problem about rouge evaluation.

```
Reading dataset data/cnndm.gz... 287089 pairs.
Vocabulary loaded, 30004 words.
29584 pre-trained embeddings loaded.
Reading dataset data/cnndm.val.gz... 13366 pairs.
Training 3609207 trainable parameters...
Epoch 1:   0% 0/1000 [00:00<?, ?it/s]/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1639: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Epoch 1: 100% 1000/1000 [1:11:31<00:00,  4.29s/it, loss=4.84341]
Valid 1:   0% 0/100 [00:00<?, ?it/s]/bin/sh: 1: ./ROUGE-1.5.5.pl: not found
Traceback (most recent call last):
  File "train.py", line 232, in <module>
    train(train_gen, v, m, p, val_gen, train_status)
  File "train.py", line 144, in train
    show_cover_loss=params.show_cover_loss)
  File "/content/drive/My Drive/Mylab/seq2seq-summarizer/test.py", line 72, in eval_batch
    scores = rouge(gold_summaries, decoded_batch)
  File "/content/drive/My Drive/Mylab/seq2seq-summarizer/utils.py", line 395, in rouge
    shell=True, cwd=os.path.join(this_dir, 'data'))
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command './ROUGE-1.5.5.pl -e data -a -n 2 -2 4 -u /tmp/tmp9eh8e5z4/task.xml' returned non-zero exit status 127.
Valid 1:   0% 0/100 [00:03<?, ?it/s]

```
I would appreciate you if you could give me some help.

**Comment by Jimmy5217** [comment]
After install rouge environment and this issue can be solved.
